### ISSUE TITLE
dynamic import("diagnostics_channel") breaks React Native / Hermes release builds

### ISSUE THREAD

**Issue by Notoriousbrain** [vercel/ai#16191]
## Summary

Importing anything from `ai` (e.g. `DefaultChatTransport`) in a React Native / Expo app fails the Hermes release bundle with:

```
error: Invalid expression encountered
  diagnosticsChannelPromise = import(/* webpackIgnore: true */ "diagnostics_channel")
```

Reproduces on `ai@7.0.0-canary.161` and `7.0.0-canary.176`. The offending `import()` is still present on `main`.

## Offending code

`packages/ai/src/telemetry/tracing-channel-publisher.ts`:

```ts
async function loadDiagnosticsChannel(): Promise<
  DiagnosticsChannel | undefined
> {
  if (!isNodeRuntime()) {
    return undefined;
  }

  if (diagnosticsChannelPromise == null) {
    diagnosticsChannelPromise = (
      import(
        /* webpackIgnore: true */
        'node:diagnostics_channel'
      ) as Promise<DiagnosticsChannel>
    ).catch(() => undefined);
  }

  return diagnosticsChannelPromise;
}
```

## Root cause

1. **Hermes' compiler (`hermesc`) does not support dynamic `import()` syntax** — it rejects it regardless of the specifier. Minimal repro, no AI SDK involved:

   ```js
   // himport.js
   var p = import("foo");
   ```

   ```
   $ hermesc -emit-binary -out himport.hbc himport.js
   himport.js:1:9: error: Invalid expression encountered
   var p = import("foo");
           ^~~~~~~~~~~~~
   ```

2. Metro can't resolve the Node builtin, so it passes the raw `import()` straight through to Hermes.
3. `/* webpackIgnore: true */` only helps webpack; Metro/Hermes don't honor it.
4. The `isNodeRuntime()` guard prevents *execution* on RN, but the `import()` is still **compiled** as dead code, so the guard doesn't help the build.
5. The package ships no `react-native` / `browser` export condition, so React Native gets the Node-flavored build.

## Reproduction

In any Expo app that imports from `ai`:

```
npx expo export --platform ios
# → index.js: error: Invalid expression encountered
#   diagnosticsChannelPromise = import(/* webpackIgnore: true */ "node:diagnostics_channel")
```

## Impact

Any React Native / Expo + Hermes app that imports **anything** from `ai` v7 (even just `DefaultChatTransport`) fails its release bundle. The diagnostics/tracing-channel telemetry was introduced in #14251 and expanded in #15660, so all current v7 canaries are affected.

## Suggested fix

The same file already has a Hermes-safe builtin loader that avoids `import()` entirely — `loadBuiltinModule`, used by `openTelemetryChannelSpanContext`:

```ts
function loadBuiltinModule<T>(id: string): T | undefined {
  const processWithBuiltins = globalThis.process as
    | { getBuiltinModule?: (id: string) => unknown }
    | undefined;
  try {
    return processWithBuiltins?.getBuiltinModule?.(id) as T | undefined;
  } catch {
    return undefined;
  }
}
```

`loadDiagnosticsChannel` can use it instead of the dynamic `import()`, which removes the `import()` expression from the bundle while keeping Node behavior identical:

```ts
async function loadDiagnosticsChannel(): Promise<
  DiagnosticsChannel | undefined
> {
  if (!isNodeRuntime()) {
    return undefined;
  }

  if (diagnosticsChannelPromise == null) {
    diagnosticsChannelPromise = Promise.resolve(
      loadBuiltinModule<DiagnosticsChannel>('node:diagnostics_channel'),
    );
  }

  return diagnosticsChannelPromise;
}
```

Happy to open a PR for this.

### AI SDK Version

- ai: 7.0.0-canary.161 (also reproduces on 7.0.0-canary.176)
- @ai-sdk/react: 4.0.0-canary.164
- expo: SDK 56 (Hermes + Metro)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Aayush-engineer** [comment]
Hi, I'd like to work on this fix. 
The suggested fix using loadBuiltinModule looks correct 
and I'll open a PR shortly.

**Comment by gr2m** [comment]
Thanks @Notoriousbrain for reporting. And thank you @Aayush-engineer and @zhsj0089944 for submitting PRs.

This looks like the correct fix to me, but I don't have React Native or Hermes to verify it works. Can one of you do it
https://github.com/vercel/ai/pull/16192/changes

@Aayush-engineer fyi with "Manual Verification" we mean that a fix was tested end-to-end. The automated tests are run anyway as part of our CI

**Comment by Notoriousbrain** [comment]
> Thanks [@Notoriousbrain](https://github.com/Notoriousbrain) for reporting. And thank you [@Aayush-engineer](https://github.com/Aayush-engineer) and [@zhsj0089944](https://github.com/zhsj0089944) for submitting PRs.
> 
> This looks like the correct fix to me, but I don't have React Native or Hermes to verify it works. Can one of you do it https://github.com/vercel/ai/pull/16192/changes
> 
> [@Aayush-engineer](https://github.com/Aayush-engineer) fyi with "Manual Verification" we mean that a fix was tested end-to-end. The automated tests are run anyway as part of our CI

can i create a pr with the changes, ive already patched the ai-sdk  in my repo and it works perfectly, so if you want i can contribute it here so i can remove the patch from ai-sdk

**Comment by gr2m** [comment]
sure share what you got @Notoriousbrain

**Comment by Aayush-engineer** [comment]
@gr2m posted manual Hermes/Android verification on #16192 if useful while reviewing the open PRs.

**Comment by Notoriousbrain** [comment]
@gr2m the pr #16192 by @Aayush-engineer has correct code, its same in my patch, its good to go

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete compatibility failure in existing SDK code that prevents React Native/Hermes applications from building, and it was handled and released as a product fix.

### Evidence
- Importing any API from `ai` v7 causes React Native/Expo Hermes release bundling to fail with `Invalid expression encountered`.
- The shipped telemetry code contains dynamic `import('node:diagnostics_channel')`, syntax that Hermes cannot compile even behind a runtime guard.
- Maintainers accepted the proposed code fix, it was manually verified on Hermes/Android, and the fix was subsequently published in `ai@7.0.11`.
