### PR TITLE
Feature/add usage data to image generation

### PR DESCRIPTION
**Pull request by kingsleytorlowei**
## Background
Make it possible to view the token usage cost after generating an image with openai ior xai provider

## Summary
examples/ai-core/src/generate-image/open-usage.ts // This currently results in a typescript error   Property 'usage' does not exist on type 'GenerateImageResult'.ts(2339)
In further commits this error will be fixed after the usgae functionality is addressed 

## Tasks
* Add usage function to generateImage
* Add more examples of usage to other providers

## Related Issues
Addresses: https://github.com/vercel/ai/issues/8358

### CODE REVIEW

**Comment by gr2m** [comment]
FYI https://github.com/vercel/ai/pull/8538. Problem is that we didn't consider usage in the v2 Image Model Spec, and we cannot change the spec in patch versions. Good news is that we will start working on v5.1 next week, meaning we will start shipping `ai@5.1.0-beta.X` releases, where we can update the spec. 

https://github.com/vercel/ai/pull/8538 is exposing the raw response body, but we might consider exposing usage data explicitly like we do in other models, e.g. 

https://github.com/vercel/ai/blob/a3b2e2791f58e8e9270a31e2bed538a718645541/packages/provider/src/language-model/v2/language-model-v2.ts#L66

https://github.com/vercel/ai/blob/7979f7fc95d4b132d7b6e820b07a24f80d72cb23/packages/provider/src/language-model/v2/language-model-v2-usage.ts#L7-L33

It would be helpful to research what usage tokens are currently returned across multiple providers and models

File: examples/ai-core/src/generate-image/open-usage.ts [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+
+async function main() {
+  const prompt = 'Santa Claus driving a Cadillac';
+  const result = await generateImage({
+    model: openai.image('dall-e-3'),
+    prompt,
+  });
+
+  // TODO: Usage tracking is not yet implemented for image generation
+  // console.log(result.usage);
```
Comment (gr2m) [inline examples/ai-core/src/generate-image/open-usage.ts]: good example 👍🏼 just rename the file to `openai-usage.ts`

**Comment by kingsleytorlowei** [comment]
@gr2m after adding the usage to the ImageModelV2, the plan would be to implement the usage data for all the providers and models right? Can i put that all in this PR?

**Comment by gr2m** [comment]
> after adding the usage to the ImageModelV2, the plan would be to implement the usage data for all the providers and models right? Can i put that all in this PR?

hold on for a few days. We will introduce a new v3 specs (side-by-side) where we can add new properties. Then we can update all the providers to use the new spec. This will be part of #8662

**Comment by kingsleytorlowei** [comment]
> > after adding the usage to the ImageModelV2, the plan would be to implement the usage data for all the providers and models right? Can i put that all in this PR?
> 
> hold on for a few days. We will introduce a new v3 specs (side-by-side) where we can add new properties. Then we can update all the providers to use the new spec. This will be part of #8662

Got it, do you need any help with the v3 spec? Anything i can take on?

**Comment by gr2m** [comment]
Maybe, I'll keep you posted. Thanks for offering!

**Comment by aayush-kapoor** [comment]
wondering if it makes sense to close this PR since different providers have different ways of calculating usage. 

This approach isn't a unified approach that we had discussed. maybe something to tackle after v6? 

cc @gr2m @lgrammel
