### ISSUE TITLE
Property '_internal' does not exist on type...

### ISSUE THREAD

**Issue by Emanuele-Fortunati** [vercel/ai#4686]
### Description

ai: 4.1.17
typescript: 5.7.3
tsconfig.json:
```
{
  "compilerOptions": {
    "outDir": "./dist",
    "module": "CommonJS",
    "target": "ES2022",
    "strict": true,
    "sourceMap": false,
    "allowJs": true,
    "esModuleInterop": true
  },
  "include": ["**/*.ts"],
  "exclude": ["node_modules", "dist", "index.old.ts"]
}
```

If I try to compile with tsc, I get lot of the following errors:

 Property '_internal' does not exist on type '{ chunks: T[]; initialDelayInMs?: number; chunkDelayInMs?: number; }'

Any idea why?

### Code example

import { CoreMessage, generateText } from 'ai';

let { text } = await generateText({
    model: openai(configuration.openAI.model),
    messages,
    temperature: 0.2,
});

**Comment by shaper** [comment]
Thank you for reporting -- we are looking at a potential revert of https://github.com/vercel/ai/pull/4561 to resolve this shortly.

**Comment by shaper** [comment]
@Emanuele-Fortunati are you perhaps able to put up a small example repo? It would be helpful for us to be able to reproduce the failure, so that if we look to reland an updated version of the change we can avoid breaking you or others again.

I tried updating a small nextjs app to `ai` 4.1.17 and it builds with typescript `5.7.3` although admittedly a slightly different tsconfig.

Apologies for the hassle, we are looking to revert in the meantime in any case.

**Comment by Emanuele-Fortunati** [comment]
> [@Emanuele-Fortunati](https://github.com/Emanuele-Fortunati) are you perhaps able to put up a small example repo? It would be helpful for us to be able to reproduce the failure, so that if we look to reland an updated version of the change we can avoid breaking you or others again.
> 
> I tried updating a small nextjs app to `ai` 4.1.17 and it builds with typescript `5.7.3` although admittedly a slightly different tsconfig.
> 
> Apologies for the hassle, we are looking to revert in the meantime in any case.

Hello, thanks for the support.
I'm travelling this week so it's a bit hard to put up a small repo, I'll do next week for sure.
(unfortunately I cannot share the full code as it belongs to a client of mine)

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete TypeScript compilation regression in the existing SDK. The maintainer's planned revert further indicates unintended broken behavior rather than a request for new functionality.

### Evidence
- Compiling an application with `ai` 4.1.17 and TypeScript 5.7.3 produces repeated errors that `_internal` does not exist on the expected type.
- A maintainer linked the failure to a recent change and stated they were considering reverting it to resolve the problem and avoid further breakage.
