### PR TITLE
fix(amazon-bedrock): omit undefined: prefix when Bedrock error body has no type

### LINKED ISSUE #20926: amazon-bedrock: API error messages are prefixed with "undefined:" when the Bedrock error body has no type
### Description

`@ai-sdk/amazon-bedrock` prefixes API error messages with the literal string `undefined:` when Bedrock's error body has no `type` field.

`AmazonBedrockErrorSchema` declares `type` as `nullish`, and Bedrock's Converse/ConverseStream 400 body is just `{"message": "..."}` (the error class is in the `x-amzn-errortype` response header, not the body). The non-streaming chat handler already guards this (`error.message ?? 'Unknown error'`), but the streaming chat handler, the embedding model, the image model, and the reranking model all format with `${error.type}: ${error.message}`.

Actual (from `doStream` against `global.openai.gpt-6-astra` with an image inside `toolResult`):

```
AI_APICallError: undefined: This model doesn't support the image field for user messages. Remove image and try again.
```

Expected: the message without the `undefined:` prefix (or with the real error type when one is present).

Consumers surface this string verbatim; e.g. OpenCode shows "undefined: This model doesn't support..." to users (anomalyco/opencode#48069).

Version: `@ai-sdk/amazon-bedrock` 4.0.166 (seen in the wild) and 5.0.86 (`main` at 7f803af).

### Reproduction

Failing test + fix in #20927. Minimal repro without the PR: point `AmazonBedrockChatLanguageModel.doStream` at a server that responds `400 {"message":"boom"}`; the rejected `APICallError.message` is `"undefined: boom"`.

### PR DESCRIPTION
**Pull request by alohaninja**
## Background

Bedrock error bodies often omit `type` (the error class lives in the `x-amzn-errortype` header), and `AmazonBedrockErrorSchema` already models `type` as nullish. The non-streaming chat handler guards for that, but the streaming chat, embedding, image, and reranking handlers format errors as `${error.type}: ${error.message}`, so users see messages like:

```
AI_APICallError: undefined: This model doesn't support the image field for user messages. Remove image and try again.
```

## Summary

- Add `amazonBedrockErrorToMessage` next to `AmazonBedrockErrorSchema`: `type` present → `"<type>: <message>"`, otherwise just `<message>`.
- Use it in all five `errorToMessage` call sites so the four models format Bedrock errors the same way.
- Add a `doStream` test that returns `400 {"message": ...}` and asserts the `APICallError` message has no `undefined:` prefix.

## Contributor Credit

Surfaced while investigating anomalyco/opencode#48069, where the `undefined:` prefix shows up in the UI.

## End-to-End Verification

Reproduced the raw Bedrock body with `aws bedrock-runtime converse --debug` against `global.openai.gpt-6-astra` in us-east-1: the 400 body is `{"message":"This model doesn't support the image field for user messages. Remove image and try again."}` with no `type`, and the published 4.0.166 build renders it as `undefined: This model doesn't support...` through OpenCode's Bedrock provider. With this change the streaming handler produces the bare message for that body.

pr20927-bedrock-error-fix

## Checklist

- [x] All commits are signed (PRs with unsigned commits cannot be merged)
- [x] Tests have been added / updated (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)
- [x] A _patch_ changeset for relevant packages has been added (for bug fixes / features - run `pnpm changeset` in the project root)
- [x] I have reviewed this pull request (self-review)

## Related Issues

Fixes #20926

### CODE REVIEW

**Review by aayush-kapoor — COMMENTED** [review]
fixed via https://github.com/vercel/ai/pull/20933
