### ISSUE TITLE
amazon-bedrock: API error messages are prefixed with "undefined:" when the Bedrock error body has no type

### ISSUE THREAD

**Issue by alohaninja** [vercel/ai#20926]
### Description

`@ai-sdk/amazon-bedrock` prefixes API error messages with the literal string `undefined:` when Bedrock's error body has no `type` field.

`AmazonBedrockErrorSchema` declares `type` as `nullish`, and Bedrock's Converse/ConverseStream 400 body is just `{"message": "..."}` (the error class is in the `x-amzn-errortype` response header, not the body). The non-streaming chat handler already guards this (`error.message ?? 'Unknown error'`), but the streaming chat handler, the embedding model, the image model, and the reranking model all format with `${error.type}: ${error.message}`.

Actual (from `doStream` against `global.openai.gpt-6-astra` with an image inside `toolResult`):

```
AI_APICallError: undefined: This model doesn't support the image field for user messages. Remove image and try again.
```

Expected: the message without the `undefined:` prefix (or with the real error type when one is present).

Consumers surface this string verbatim; e.g. OpenCode shows "undefined: This model doesn't support..." to users (anomalyco/opencode#48069).

Version: `@ai-sdk/amazon-bedrock` 4.0.166 (seen in the wild) and 5.0.86 (`main` at 7f803af).

### Reproduction

Failing test + fix in #20927. Minimal repro without the PR: point `AmazonBedrockChatLanguageModel.doStream` at a server that responds `400 {"message":"boom"}`; the rejected `APICallError.message` is `"undefined: boom"`.
